apiVersion: v1
kind: Service
metadata: 
  name: prometheus-0-service
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    name: prometheus
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector: 
    statefulset.kubernetes.io/pod-name: prometheus-0
  ports: 
    - name: prometheus 
      port: 8080
      targetPort: prometheus

---

#This service creates a srv record for querier to find about store-api's
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-api-grpc
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: prometheus-api-grpc
spec:
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-0
  type: NodePort
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
    nodePort: 30006
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-api-store
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: prometheus-api-store
spec:
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-0
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 30007
    protocol: TCP
---

